name: Build linux-aw2501

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install devcontainer build tools
        run: |
          sudo apt update
          sudo apt install -y devscripts build-essential debhelper fakeroot \
            bc bison flex libssl-dev gcc-aarch64-linux-gnu

      - name: Build kernel deb
        run: |
          make deb

      - name: Upload built deb packages
        uses: actions/upload-artifact@v4
        with:
          name: kernel-debs
          path: "*.deb"
