name: Build linux-aw2501

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/devcontainers/base:bookworm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build deb
        run: |
          make deb

      - name: Upload debs
        uses: actions/upload-artifact@v4
        with:
          name: linux-aw2501-debs
          path: "*.deb"
